# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20160213_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitation_user', to='social.Member'),
        ),
    ]
